name: Create r2m PR

on:
  push:
    branches:
      - release

jobs:
  r2m-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Execute gir-pr-release (release -> main)
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem install git-pr-release
          git-pr-release || echo "Done."
