name: Create r2m PR

on:
  push:
    branches:
      - release

jobs:
  r2m-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Execute gir-pr-release (release -> master)
        run: |
          gh pr create -B main -t release -b ""
